### ISSUE TITLE
import doesn't work: not found error no matter what you do

### ISSUE THREAD

**Issue by PS-davetemplin** [schibsted/jslt#134]
```
import "utilities.jslt" as utils

{ * : . }
```

Got error below. File `utilities.jslt` absolutely, positively, definitely exists.
```
Exception in thread "main" com.schibsted.spt.data.jslt.JsltException: Cannot load resource 'utilities.jslt': not found
        at com.schibsted.spt.data.jslt.impl.ClasspathResourceResolver.resolve(ClasspathResourceResolver.java:42)
        at com.schibsted.spt.data.jslt.parser.ParserImpl.compileImport(ParserImpl.java:70)
        at com.schibsted.spt.data.jslt.parser.ParserImpl.doImport(ParserImpl.java:590)
        at com.schibsted.spt.data.jslt.parser.ParserImpl.processImports(ParserImpl.java:576)
        at com.schibsted.spt.data.jslt.parser.ParserImpl.compile(ParserImpl.java:93)
        at com.schibsted.spt.data.jslt.parser.ParserImpl.compileExpression(ParserImpl.java:55)
        at com.schibsted.spt.data.jslt.Parser.compile(Parser.java:226)
        at com.schibsted.spt.data.jslt.Parser.compile(Parser.java:62)
        at com.schibsted.spt.data.jslt.Parser.compile(Parser.java:51)
        at com.schibsted.spt.data.jslt.cli.JSLT.main(JSLT.java:33)
```

**Comment by larsga** [comment]
I'm sure the file exists, but by default JSLT will only load modules from the classpath. So you have to use the API and give the parser a `FileSystemResourceResolver` for it to look for files on disk.

**Comment by PS-davetemplin** [comment]
Thanks for the clarification. As a user I would expect the tool to load import references relative to where the referencing file exists first and foremost. I would also hope relative paths work.

**Comment by larsga** [comment]
In the general case loading things from the file system could open all kinds of security holes, which we'd rather avoid. We could use the file system resolver in the command-line client, I guess. As you say it would make sense. A question is whether users would then be confused when the library behaves differently from the CLI.

**Comment by RahulKesharwani353** [comment]
> I'm sure the file exists, but by default JSLT will only load modules from the classpath. So you have to use the API and give the parser a `FileSystemResourceResolver` for it to look for files on disk.

How to use this API inside my Java Spring boot application. As I have utils.jslt inside my "com.example.demo" folder

**Comment by larsga** [comment]
@RahulKesharwani353 The API will work the exact same way inside Spring boot as it does outside Spring boot. `FileSystemResourceResolver` will load from files on the file system. Tbh, I'm not sure what your question is.

**Comment by RahulKesharwani353** [comment]
@larsga actually I unable to use import statement inside JSLT expression, and I have no idea how to resolve it. Can you please help to solve this

**Comment by larsga** [comment]
You need to explain what you're doing. Otherwise nobody can tell what is wrong.

**Comment by RahulKesharwani353** [comment]
Hey see !

I have made an template.jslt and importing it on my string
![image](https://user-images.githubusercontent.com/65972077/220292276-f0f2df74-7e04-4921-8cdf-fd7176c7b401.png)

and this is my folder structure 

![image](https://user-images.githubusercontent.com/65972077/220292543-d3a9b5c9-3f9f-40e1-99ac-39601439c06b.png)


when I execute the code, I am getting the same error

**Comment by larsga** [comment]
There are two problems.

JSLT will try to load your `.jslt` file from the classpath, but you haven't placed it on the classpath. You've placed it with the source code. So the `.jslt` file is not in your `.jar` file.

The `.` in the import statement will be interpreted as `.`, so you won't be able to find the file way down in the folder structure.

To start with, here's what I would do. Move the file to `src/main/resources/template.jslt`. Then change the import statement to `import "template.jslt"`. Then try again.

If you want to move the file into subfolders of `resources` then you need to use `/` to separate the folder names, not `.`.

**Comment by RahulKesharwani353** [comment]
okay cool, Thankyou soo mush, it works.

**Comment by RahulKesharwani353** [comment]
Hey @larsga 

previous solution works ! But I am stucked again 

before building it was working . as I dockerized the project, Import Statement fails lo load the file while running the docker  container . here is my target folder 
![image](https://user-images.githubusercontent.com/65972077/221772975-eef8ca8c-e115-4b05-bc1d-26165e3fc2c1.png)

Here is docker file :
![image](https://user-images.githubusercontent.com/65972077/221773134-23b36385-30fb-49d1-8295-1bcaf4790db7.png)

and here is src folder 
![image](https://user-images.githubusercontent.com/65972077/221773277-7fb352c0-2fc2-4c71-b8f0-5f78c9b611dd.png)

**Comment by larsga** [comment]
Look inside `app.jar` (it's just a zip file) to see if `utils.jslt` is in the top level. If you then import it as `"utils.jslt"` it should work.

**Comment by RahulKesharwani353** [comment]
I guess it is in top level 
![image](https://user-images.githubusercontent.com/65972077/221781470-b9206529-d286-47a9-a648-2311355944e4.png)
but still not working

**Comment by larsga** [comment]
Looks like it's not in the top level, but in `BOOT-INF/classes`?

**Comment by sahilsh1** [comment]
Exception in thread "main" com.schibsted.spt.data.jslt.JsltException: Cannot load resource 'jslt-utils.jslt': not found
import "jslt-utils.jslt" as app

let source = .env.source
let locale = .env.locale
let val = .record

{


}

**Comment by RahulKesharwani353** [comment]
hey @sahilsh1 refer to this https://github.com/schibsted/jslt/issues/134#issuecomment-1438081800
