### ISSUE TITLE
Built-in sha256-hex function is not thread-safe

### ISSUE THREAD

**Issue by tlfdz** [schibsted/jslt#261]
The sha256-hex function is put on a static map:

https://github.com/schibsted/jslt/blob/6377fcc31796a550a079f3ef3aa863a0f75454d7/core/src/main/java/com/schibsted/spt/data/jslt/impl/BuiltinFunctions.java#L69
https://github.com/schibsted/jslt/blob/6377fcc31796a550a079f3ef3aa863a0f75454d7/core/src/main/java/com/schibsted/spt/data/jslt/impl/BuiltinFunctions.java#L100

This means there's a single instance of MessageDigest that is shared between threads, but [MessageDigest isn't thread-safe](https://www.baeldung.com/sha-256-hashing-java#message-digest). 
https://github.com/schibsted/jslt/blob/6377fcc31796a550a079f3ef3aa863a0f75454d7/core/src/main/java/com/schibsted/spt/data/jslt/impl/BuiltinFunctions.java#L518

I wrote a small example that reproduces the problem. Please add the code below to `core/src/test/java/com/schibsted/spt/data/jslt/StaticTests.java` and run the test a few times. You may try a higher number of threads to increase the likelihood of the problem happening.

<details>
  <summary>com.schibsted.spt.data.jslt.StaticTests#sha256ConcurrencyTest</summary>

```java
import com.fasterxml.jackson.core.JsonProcessingException;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;

 @Test
  public void sha256ConcurrencyTest() throws InterruptedException {

    int threads = 16;
    ExecutorService service = Executors.newFixedThreadPool(threads);
    Set<Exception> exceptionsThrown = ConcurrentHashMap.newKeySet();

    for (int i = 0; i < threads; i++) {
      service.submit(() -> {
        String input = "[{\"a\":null,\"b\":\"b\"}]";

        String expression = "\n"
            + "  {\n"
            + "    \"a\": .a,\n"
            + "    \"b\": .b,\n"
            + "    \"c\": sha256-hex(random()),\n"
            + "  }\n"
            + "  ";

        try {
          JsonNode jsonInputEvents = mapper.readTree(input);
          for (JsonNode jsonInputEvent : jsonInputEvents) {
            Expression expr = Parser.compileString(expression);
            expr.apply(jsonInputEvents);
          }

        } catch (ArrayIndexOutOfBoundsException e) {
          e.printStackTrace();
          exceptionsThrown.add(e);
        } catch (JsonProcessingException e) {
          throw new RuntimeException(e);
        }

      });
    }
    service.shutdown();
    service.awaitTermination(Long.MAX_VALUE, TimeUnit.NANOSECONDS);

    assertTrue(exceptionsThrown.isEmpty());
  }
```
</details>

I ran it just now, and got these two exceptions:

<details>
  <summary>java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -29 is negative</summary>

```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -29 is negative
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/sun.security.provider.DigestBase.engineUpdate(DigestBase.java:118)
	at java.base/java.security.MessageDigest$Delegate.engineUpdate(MessageDigest.java:622)
	at java.base/java.security.MessageDigest.update(MessageDigest.java:354)
	at java.base/java.security.MessageDigest.digest(MessageDigest.java:429)
	at com.schibsted.spt.data.jslt.impl.BuiltinFunctions$Sha256.call(BuiltinFunctions.java:531)
	at com.schibsted.spt.data.jslt.impl.FunctionExpression.apply(FunctionExpression.java:56)
	at com.schibsted.spt.data.jslt.impl.PairExpression.apply(PairExpression.java:52)
	at com.schibsted.spt.data.jslt.impl.ObjectExpression.apply(ObjectExpression.java:89)
	at com.schibsted.spt.data.jslt.impl.ExpressionImpl.apply(ExpressionImpl.java:91)
	at com.schibsted.spt.data.jslt.impl.ExpressionImpl.apply(ExpressionImpl.java:73)
	at com.schibsted.spt.data.jslt.StaticTests.lambda$sha256ConcurrencyTest$0(StaticTests.java:98)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
</details>

<details>
  <summary>java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 93 out of bounds for byte[64]</summary>

```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 93 out of bounds for byte[64]
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/sun.security.provider.DigestBase.engineUpdate(DigestBase.java:118)
	at java.base/sun.security.provider.SHA2.implDigest(SHA2.java:107)
	at java.base/sun.security.provider.DigestBase.engineDigest(DigestBase.java:210)
	at java.base/sun.security.provider.DigestBase.engineDigest(DigestBase.java:189)
	at java.base/java.security.MessageDigest$Delegate.engineDigest(MessageDigest.java:638)
	at java.base/java.security.MessageDigest.digest(MessageDigest.java:384)
	at java.base/java.security.MessageDigest.digest(MessageDigest.java:430)
	at com.schibsted.spt.data.jslt.impl.BuiltinFunctions$Sha256.call(BuiltinFunctions.java:531)
	at com.schibsted.spt.data.jslt.impl.FunctionExpression.apply(FunctionExpression.java:56)
	at com.schibsted.spt.data.jslt.impl.PairExpression.apply(PairExpression.java:52)
	at com.schibsted.spt.data.jslt.impl.ObjectExpression.apply(ObjectExpression.java:89)
	at com.schibsted.spt.data.jslt.impl.ExpressionImpl.apply(ExpressionImpl.java:91)
	at com.schibsted.spt.data.jslt.impl.ExpressionImpl.apply(ExpressionImpl.java:73)
	at com.schibsted.spt.data.jslt.StaticTests.lambda$sha256ConcurrencyTest$0(StaticTests.java:98)
```
</details>

If I lower the number of threads to 1, I couldn't reproduce it.

Searching for `ArrayIndexOutOfBoundsException MessageDigest`, you'll find several results where it's claimed that this is indeed a thread-safety issue.

**Comment by larsga** [comment]
From googling a little and looking at the `MessageDigest` source it looks like this may be good enough.

Thoughts @fuchsst?

**Comment by larsga** [comment]
We have people asking for a release of a fix: discussion #263

@fuchsst and @tlfdz: any thoughts on the fix I merged? If not, I'll just release the fix.

**Comment by fuchsst** [comment]
lgtm

**Comment by larsga** [comment]
Great, then let's close. This issue.
